## ㅁOne Point Tutorial V
# `Data Manipulation`
<p style='text-align: right;'> 빅데이터 분석 중고급과정 with 관악구, KMR</p>
<p style='text-align: right;'> 2023 2nd | All rights reserved by Wooseok Song</p>

---

In [3]:
# !pip install pathlib
# !pip install xlrd
# !pip3 install openpyxl
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [4]:
try:
    os.chdir("C:/Users/32193392/Desktop/datascience/sample_data/sample_data/")
    print("Directory changed")
except OSError:
    print("Can't change the Current Working Directory")  

Directory changed


In [5]:
folder = Path('C:/Users/32193392/Desktop/datascience/sample_data/sample_data/')
file_path_output = folder / "output.txt"
file_path_output

WindowsPath('C:/Users/32193392/Desktop/datascience/sample_data/sample_data/output.txt')

In [6]:
# 1. 텍스트 파일을 불러보자.
pd.read_table("people.txt", sep = ' ', header = 0, encoding = "UTF-8")

name age gender bloodtype
0   Kim  34      F         A
1  Yoon  22      M         O
2  Park  50      M        AB
3   Lee  17      F         B
4   Min   .      F         O
5  Kang  39      M         A
6   Lim  42      M         O

In [7]:
## 불러온 텍스트 파일을 그릇에 담고 싶다면?
txt_table = pd.read_table('output.txt', sep=' ', header=0, encoding = "UTF-8")

In [8]:
## 기본적으로 어떤 type으로 오브젝트에 저장 되는지 확인해보자.
type(txt_table)

pandas.core.frame.DataFrame

In [9]:
# 2. 엑셀 파일을 불러 객체에 할당해보자.
excel_table = pd.read_excel('Financial Sample.xlsx')
excel_table

Country    Product  Units Sold  Sale Price  Gross Sales  \
0                     Canada  Carretera      1618.5          20      32370.0   
1                    Germany  Carretera      1321.0          20      26420.0   
2                     France  Carretera      2178.0          15      32670.0   
3                    Germany  Carretera       888.0          15      13320.0   
4                     Mexico  Carretera      2470.0          15      37050.0   
5                    Germany  Carretera      1513.0         350     529550.0   
6                    Germany    Montana       921.0          15      13815.0   
7                     Canada    Montana      2518.0          12      30216.0   
8                     France    Montana      1899.0          20      37980.0   
9                    Germany    Montana      1545.0          12      18540.0   
10                    Mexico    Montana      2470.0          15      37050.0   
11                    Canada    Montana      2665.5         125     333187.5   
12                    Mexico    Montana       958.0         300     287400.0   
13                   Germany    Montana      2146.0           7      15022.0   
14                    Canada    Montana       345.0         125      43125.0   
15  United States of America    Montana       615.0          15       9225.0   
16                    Canada      Paseo       292.0          20       5840.0   
17                    Mexico      Paseo       974.0          15      14610.0   
18                    Canada      Paseo      2518.0          12      30216.0   

       Sales    COGS    Profit  Month Number Month Name  Year  
0    32370.0   16185   16185.0             1    January  2014  
1    26420.0   13210   13210.0             1    January  2014  
2    32670.0   21780   10890.0             6       June  2014  
3    13320.0    8880    4440.0             6       June  2014  
4    37050.0   24700   12350.0             6       June  2014  
5   529550.0  393380  136170.0            12   December  2014  
6    13815.0    9210    4605.0             3      March  2014  
7    30216.0    7554   22662.0             6       June  2014  
8    37980.0   18990   18990.0             6       June  2014  
9    18540.0    4635   13905.0             6       June  2014  
10   37050.0   24700   12350.0             6       June  2014  
11  333187.5  319860   13327.5             7       July  2014  
12  287400.0  239500   47900.0             8     August  2014  
13   15022.0   10730    4292.0             9  September  2014  
14   43125.0   41400    1725.0            10    October  2013  
15    9225.0    6150    3075.0            12   December  2014  
16    5840.0    2920    2920.0             2   February  2014  
17   14610.0    9740    4870.0             2   February  2014  
18   30216.0    7554   22662.0             6       June  2014

In [10]:
# 3. csv 파일을 불러 오브젝트에 할당해보자.
csv_table = pd.read_csv('gender_submission.csv')
csv_table

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [11]:
# 4. Titanic 데이터를 Kaggle.com에서 다운 받은 다음 import하여 객체에 할당해보자.
titanic_raw = pd.read_csv('train.csv')
titanic_raw

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [12]:
# 잠시 타이타닉은 잊고, 행과 열에 이름을 부여해보자.
# 5. Row/Column Naming
sr1 = pd.Series([1,2,3,4])
sr1.index = ['a', 'b', 'c', 'd']
sr1

a    1
b    2
c    3
d    4
dtype: int64

In [13]:
df1 = pd.DataFrame(np.arange(10).reshape(5,2))
df1.index = list('abcde')
df1.columns = ['A', 'B']
df1

A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

In [14]:
# 6. Indexing
sr1.iloc[1:3]

b    2
c    3
dtype: int64

In [15]:
sr1.loc[['b', 'c']]

b    2
c    3
dtype: int64

In [16]:
df1.iloc[3, 0:2]

A    6
B    7
Name: d, dtype: int32

In [17]:
df1.loc['b']

A    2
B    3
Name: b, dtype: int32

In [18]:
df1.loc['B']

KeyError: 'B'

In [ ]:
df1.loc[:, 'B']

a    1
b    3
c    5
d    7
e    9
Name: B, dtype: int64

In [ ]:
df1.loc[:]['B']

a    1
b    3
c    5
d    7
e    9
Name: B, dtype: int64

In [ ]:
# 본격적으로 벡터의 부분집합(서브셋)을 만들어보자.
# 7. Subsetting for vectors

v0 = pd.Series([1, 2, 3, 4, 5, 6])

# Single Element
print(v0[0]); print(v0[1])

1
2


In [ ]:
# Sequence Elements
v0[1:5]

1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# Multiple Elements
v0[[1, 3, 5]]

1    2
3    4
5    6
dtype: int64

In [ ]:
# Logical Sequence Elements
larger_2 = v0 > 2
larger_2

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [ ]:
v0[larger_2]

2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
# 데이터 프레임의 부분집합을 만들어보자.
# 8.Subsetting for data.frame
df1 = pd.DataFrame({'mid' : [100, 92, 93],
                    'final' : [93, 94, 95]})
df1.shape

(3, 2)

In [ ]:
df1.iloc[1, 0]

92

In [ ]:
type(df1.iloc[1, 0])

numpy.int64

In [ ]:
df1.iloc[[1],[0]]

mid
1   92

In [ ]:
type(df1.iloc[[1],[0]])

pandas.core.frame.DataFrame

In [ ]:
df1.iloc[2, :]

A    4
B    5
Name: c, dtype: int32

In [ ]:
df1.iloc[:, 1]

a    1
b    3
c    5
d    7
e    9
Name: B, dtype: int32

In [ ]:
df1.iloc[1, 0:2]

A    2
B    3
Name: b, dtype: int32

In [ ]:
# Matrix vs. Data Frame
mat1 = np.array(df1.values)
mat1[1, 0]

2

In [ ]:
df1.iloc[1, 0] == mat1[1, 0]

True

In [ ]:
# 리스트도 부분집합을 만들어보자.
# 9. Subsetting for Lists
ls2 = [[1, 2, 3], np.arange(1,10).reshape(3,3)]
ls2

[[1, 2, 3],
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [ ]:
ls2[1][0:3, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
# 합쳐보자.
# 10. Merging
# 10.1. Concatenate
ma = np.arange(1, 7).reshape(2, 3)
mb = np.arange(7, 13).reshape(2, 3)
print(ma, '\n', mb)

[[1 2 3]
 [4 5 6]] 
 [[ 7  8  9]
 [10 11 12]]


In [ ]:
ma_nrow, ma_ncol = ma.shape
print(ma_nrow, ma_ncol)

2 3


In [ ]:
mb_nrow, mb_ncol = mb.shape
print(mb_nrow, mb_ncol)

2 3


In [ ]:
mm = np.empty((ma_nrow + mb_nrow, ma_ncol)) * np.nan
mm

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [ ]:
mm[:ma_nrow, :] =  ma
mm

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [nan, nan, nan],
       [nan, nan, nan]])

In [ ]:
mm[ma_nrow:ma_nrow + mb_nrow, :] = mb
mm

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
mm2 = np.empty((ma_nrow, ma_ncol + mb_ncol)) * np.nan # 2 X 6 NA
mm2

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [ ]:
mm2[:, :ma_ncol] =  ma
mm2

array([[ 1.,  2.,  3., nan, nan, nan],
       [ 4.,  5.,  6., nan, nan, nan]])

In [ ]:
mm2[:, ma_ncol:ma_ncol + mb_ncol] = mb
mm2

array([[ 1.,  2.,  3.,  7.,  8.,  9.],
       [ 4.,  5.,  6., 10., 11., 12.]])

In [ ]:
#Q. np.concatenate((array, array), axis= 0 or 1)을 사용하여 만들어보라. 
np.concatenate((ma, mb), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.concatenate((ma, mb), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
## Join을 배워보자.

##### Join
df1 = pd.DataFrame({'CustomerId' : range(1, 11),
     'Menu' : ("Kimbab " * 3 + "Bibimbab " * 3 + "Odeng " * 4).split()})
df1

CustomerId      Menu
0           1    Kimbab
1           2    Kimbab
2           3    Kimbab
3           4  Bibimbab
4           5  Bibimbab
5           6  Bibimbab
6           7     Odeng
7           8     Odeng
8           9     Odeng
9          10     Odeng

In [ ]:
df2 = pd.DataFrame({'CustomerId' : [2, 4, 6],
     'Table' : ("SectorA " * 2 + "SectorB").split()})
df2

CustomerId    Table
0           2  SectorA
1           4  SectorA
2           6  SectorB

In [ ]:
df3 = pd.DataFrame({'CustomerId' : [2, 5], 'Gender' : ["Male", "Female"]})
df3

CustomerId  Gender
0           2    Male
1           5  Female

In [ ]:
## Inner Join
InnerJoined = pd.merge(df1, df2, on = "CustomerId")
InnerJoined

CustomerId      Menu    Table
0           2    Kimbab  SectorA
1           4  Bibimbab  SectorA
2           6  Bibimbab  SectorB

In [ ]:
InnerJoined2 = InnerJoined.merge(df3, on="CustomerId")
InnerJoined2

CustomerId    Menu    Table Gender
0           2  Kimbab  SectorA   Male

In [ ]:
InnerJoined3 = pd.merge(df1, df2, on = "CustomerId").merge(df3, on='CustomerId')
InnerJoined3

CustomerId    Menu    Table Gender
0           2  Kimbab  SectorA   Male

In [ ]:
## Left Outer Join
LeftOuterJoined = pd.merge(df1, df2, on="CustomerId", how='left')
LeftOuterJoined

CustomerId      Menu    Table
0           1    Kimbab      NaN
1           2    Kimbab  SectorA
2           3    Kimbab      NaN
3           4  Bibimbab  SectorA
4           5  Bibimbab      NaN
5           6  Bibimbab  SectorB
6           7     Odeng      NaN
7           8     Odeng      NaN
8           9     Odeng      NaN
9          10     Odeng      NaN

In [ ]:
## Right Outer Join
RightOuterJoined = pd.merge(df1, df2, on = "CustomerId", how = 'right')
RightOuterJoined

CustomerId      Menu    Table
0           2    Kimbab  SectorA
1           4  Bibimbab  SectorA
2           6  Bibimbab  SectorB

In [ ]:
RightOuterJoined2 = df1.merge(df2, on = "CustomerId", how = 'right')
RightOuterJoined2

CustomerId      Menu    Table
0           2    Kimbab  SectorA
1           4  Bibimbab  SectorA
2           6  Bibimbab  SectorB

In [ ]:
## Outer Join
OuterJoined = pd.merge(df1, df2, on = "CustomerId", how = 'outer')
OuterJoined

CustomerId      Menu    Table
0           1    Kimbab      NaN
1           2    Kimbab  SectorA
2           3    Kimbab      NaN
3           4  Bibimbab  SectorA
4           5  Bibimbab      NaN
5           6  Bibimbab  SectorB
6           7     Odeng      NaN
7           8     Odeng      NaN
8           9     Odeng      NaN
9          10     Odeng      NaN

In [ ]:
OuterJoined2 = pd.merge(OuterJoined, df3, on = "CustomerId", how = 'outer')
OuterJoined2

CustomerId      Menu    Table  Gender
0           1    Kimbab      NaN     NaN
1           2    Kimbab  SectorA    Male
2           3    Kimbab      NaN     NaN
3           4  Bibimbab  SectorA     NaN
4           5  Bibimbab      NaN  Female
5           6  Bibimbab  SectorB     NaN
6           7     Odeng      NaN     NaN
7           8     Odeng      NaN     NaN
8           9     Odeng      NaN     NaN
9          10     Odeng      NaN     NaN

In [ ]:
## dplyr:select
titanic_raw = pd.read_csv('train.csv')
titanic_raw.shape

(891, 12)

In [ ]:
titanic_raw.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
name = titanic_raw.columns[:5]
titanic_subset = titanic_raw.loc[:, name]
titanic_subset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  
0                              Braund, Mr. Owen Harris    male  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                               Heikkinen, Miss. Laina  female  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                             Allen, Mr. William Henry    male  
..                                                 ...     ...  
886                              Montvila, Rev. Juozas    male  
887                       Graham, Miss. Margaret Edith  female  
888           Johnston, Miss. Catherine Helen "Carrie"  female  
889                              Behr, Mr. Karl Howell    male  
890                                Dooley, Mr. Patrick    male  

[891 rows x 5 columns]

In [ ]:
titanic_subset2 = titanic_raw.loc[:, 'PassengerId':'Sex']
titanic_subset2

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  
0                              Braund, Mr. Owen Harris    male  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                               Heikkinen, Miss. Laina  female  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                             Allen, Mr. William Henry    male  
..                                                 ...     ...  
886                              Montvila, Rev. Juozas    male  
887                       Graham, Miss. Margaret Edith  female  
888           Johnston, Miss. Catherine Helen "Carrie"  female  
889                              Behr, Mr. Karl Howell    male  
890                                Dooley, Mr. Patrick    male  

[891 rows x 5 columns]

In [ ]:
titanic_subset == titanic_subset2

PassengerId  Survived  Pclass  Name   Sex
0           True      True    True  True  True
1           True      True    True  True  True
2           True      True    True  True  True
3           True      True    True  True  True
4           True      True    True  True  True
..           ...       ...     ...   ...   ...
886         True      True    True  True  True
887         True      True    True  True  True
888         True      True    True  True  True
889         True      True    True  True  True
890         True      True    True  True  True

[891 rows x 5 columns]

In [ ]:
titanic_subset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  
0                            Braund, Mr. Owen Harris    male  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                             Heikkinen, Miss. Laina  female  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                           Allen, Mr. William Henry    male

In [ ]:
titanic_subset2 = titanic_subset2.drop('Name', axis=1)
titanic_subset2

PassengerId  Survived  Pclass     Sex
0              1         0       3    male
1              2         1       1  female
2              3         1       3  female
3              4         1       1  female
4              5         0       3    male
..           ...       ...     ...     ...
886          887         0       2    male
887          888         1       1  female
888          889         0       3  female
889          890         1       1    male
890          891         0       3    male

[891 rows x 4 columns]

In [ ]:
## 특정 문자열로 시작하거나 끝나는 열을 뽑으려면?
titanic_raw.columns.str.startswith('S')

array([False,  True, False, False,  True, False,  True, False, False,
       False, False, False])

In [ ]:
titanic_raw.columns.str.endswith('s')

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])

In [ ]:
## dplyr:filter
titanic_filtered_adult = titanic_raw[titanic_raw.Age > 18]
titanic_filtered_adult

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[575 rows x 12 columns]

In [ ]:
titanic_filtered_adult.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 575 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  575 non-null    int64  
 1   Survived     575 non-null    int64  
 2   Pclass       575 non-null    int64  
 3   Name         575 non-null    object 
 4   Sex          575 non-null    object 
 5   Age          575 non-null    float64
 6   SibSp        575 non-null    int64  
 7   Parch        575 non-null    int64  
 8   Ticket       575 non-null    object 
 9   Fare         575 non-null    float64
 10  Cabin        162 non-null    object 
 11  Embarked     573 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 58.4+ KB


In [ ]:
titanic_filtered_adult.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic_filtered_children = titanic_raw[titanic_raw.Age <= 18]
titanic_filtered_children

PassengerId  Survived  Pclass                                  Name  \
7              8         0       3        Palsson, Master. Gosta Leonard   
9             10         1       2   Nasser, Mrs. Nicholas (Adele Achem)   
10            11         1       3       Sandstrom, Miss. Marguerite Rut   
14            15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   
16            17         0       3                  Rice, Master. Eugene   
..           ...       ...     ...                                   ...   
852          853         0       3               Boulos, Miss. Nourelain   
853          854         1       1             Lines, Miss. Mary Conover   
855          856         1       3            Aks, Mrs. Sam (Leah Rosen)   
869          870         1       3       Johnson, Master. Harold Theodor   
875          876         1       3      Najib, Miss. Adele Kiamie "Jane"   

        Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
7      male   2.0      3      1    349909  21.0750   NaN        S  
9    female  14.0      1      0    237736  30.0708   NaN        C  
10   female   4.0      1      1   PP 9549  16.7000    G6        S  
14   female  14.0      0      0    350406   7.8542   NaN        S  
16     male   2.0      4      1    382652  29.1250   NaN        Q  
..      ...   ...    ...    ...       ...      ...   ...      ...  
852  female   9.0      1      1      2678  15.2458   NaN        C  
853  female  16.0      0      1  PC 17592  39.4000   D28        S  
855  female  18.0      0      1    392091   9.3500   NaN        S  
869    male   4.0      1      1    347742  11.1333   NaN        S  
875  female  15.0      0      0      2667   7.2250   NaN        C  

[139 rows x 12 columns]

In [ ]:
titanic_filtered_children.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 139 entries, 7 to 875
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  139 non-null    int64  
 1   Survived     139 non-null    int64  
 2   Pclass       139 non-null    int64  
 3   Name         139 non-null    object 
 4   Sex          139 non-null    object 
 5   Age          139 non-null    float64
 6   SibSp        139 non-null    int64  
 7   Parch        139 non-null    int64  
 8   Ticket       139 non-null    object 
 9   Fare         139 non-null    float64
 10  Cabin        23 non-null     object 
 11  Embarked     139 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 14.1+ KB


In [ ]:
titanic_filtered_children.head()

PassengerId  Survived  Pclass                                  Name  \
7             8         0       3        Palsson, Master. Gosta Leonard   
9            10         1       2   Nasser, Mrs. Nicholas (Adele Achem)   
10           11         1       3       Sandstrom, Miss. Marguerite Rut   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   
16           17         0       3                  Rice, Master. Eugene   

       Sex   Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
7     male   2.0      3      1   349909  21.0750   NaN        S  
9   female  14.0      1      0   237736  30.0708   NaN        C  
10  female   4.0      1      1  PP 9549  16.7000    G6        S  
14  female  14.0      0      0   350406   7.8542   NaN        S  
16    male   2.0      4      1   382652  29.1250   NaN        Q

In [ ]:
titanic_filtered_adult.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   575.000000  575.000000  575.000000  575.000000  575.000000   
mean    449.328696    0.382609    2.158261   34.287826    0.332174   
std     254.405068    0.486447    0.851928   11.988352    0.574661   
min       1.000000    0.000000    1.000000   19.000000    0.000000   
25%     232.500000    0.000000    1.000000   25.000000    0.000000   
50%     448.000000    0.000000    2.000000   31.000000    0.000000   
75%     665.500000    1.000000    3.000000   41.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  575.000000  575.000000  
mean     0.309565   35.224840  
std      0.816743   55.476982  
min      0.000000    0.000000  
25%      0.000000    8.050000  
50%      0.000000   14.400000  
75%      0.000000   33.760400  
max      6.000000  512.329200

In [ ]:
titanic_filtered_adult.describe(include = np.object)

Name   Sex Ticket        Cabin Embarked
count                   575   575    575          162      573
unique                  575     2    491          126        3
top     Ross, Mr. John Hugo  male  19950  C23 C25 C27        S
freq                      1   382      4            4      451

In [ ]:
titanic_filtered_children.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   139.000000  139.000000  139.000000  139.000000  139.000000   
mean    445.496403    0.503597    2.561151   10.717050    1.258993   
std     278.724719    0.501795    0.692769    6.465828    1.547968   
min       8.000000    0.000000    1.000000    0.420000    0.000000   
25%     183.500000    0.000000    2.000000    4.000000    0.000000   
50%     436.000000    1.000000    3.000000   13.000000    1.000000   
75%     712.000000    1.000000    3.000000   17.000000    2.000000   
max     876.000000    1.000000    3.000000   18.000000    5.000000   

            Parch        Fare  
count  139.000000  139.000000  
mean     0.935252   32.500721  
std      0.818346   40.759691  
min      0.000000    6.495800  
25%      0.000000   10.816650  
50%      1.000000   20.250000  
75%      2.000000   32.193750  
max      3.000000  262.375000

In [ ]:
titanic_filtered_children.describe(include = np.object)

Name   Sex   Ticket    Cabin Embarked
count                          139   139      139       23      139
unique                         139     2      104       17        3
top     Strom, Miss. Telma Matilda  male  CA 2144  B96 B98        S
freq                             1    71        5        2      103

In [ ]:
### Q) 필터를 이용하여 성인 남성 테이블/아동 남성 테이블 및 
###    성인 여성 테이블/아동 여성 테이블을 생성하라

In [ ]:
titanic_raw[(titanic_raw.Sex == 'male') & (titanic_raw.Age > 18)]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
12            13         0       3  Saundercock, Mr. William Henry  male   
13            14         0       3     Andersson, Mr. Anders Johan  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
6    54.0      0      0             17463  51.8625   E46        S  
12   20.0      0      0         A/5. 2151   8.0500   NaN        S  
13   39.0      1      5            347082  31.2750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[382 rows x 12 columns]

In [ ]:
titanic_raw[(titanic_raw.Sex == 'male') & (titanic_raw.Age <= 18)]

PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard   
16            17         0       3                     Rice, Master. Eugene   
50            51         0       3               Panula, Master. Juha Niilo   
59            60         0       3       Goodwin, Master. William Frederick   
63            64         0       3                    Skoog, Master. Harald   
..           ...       ...     ...                                      ...   
834          835         0       3                   Allum, Mr. Owen George   
841          842         0       2                 Mudd, Mr. Thomas Charles   
844          845         0       3                      Culumovic, Mr. Jeso   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
869          870         1       3          Johnson, Master. Harold Theodor   

      Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked  
7    male   2.0      3      1       349909  21.0750   NaN        S  
16   male   2.0      4      1       382652  29.1250   NaN        Q  
50   male   7.0      4      1      3101295  39.6875   NaN        S  
59   male  11.0      5      2      CA 2144  46.9000   NaN        S  
63   male   4.0      3      2       347088  27.9000   NaN        S  
..    ...   ...    ...    ...          ...      ...   ...      ...  
834  male  18.0      0      0         2223   8.3000   NaN        S  
841  male  16.0      0      0  S.O./P.P. 3  10.5000   NaN        S  
844  male  17.0      0      0       315090   8.6625   NaN        S  
850  male   4.0      4      2       347082  31.2750   NaN        S  
869  male   4.0      1      1       347742  11.1333   NaN        S  

[71 rows x 12 columns]

In [ ]:
titanic_raw[(titanic_raw.Sex == 'female') & (titanic_raw.Age > 18)]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
11            12         1       1   
..           ...       ...     ...   
879          880         1       1   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
11       0            113783  26.5500  C103        S  
..     ...               ...      ...   ...      ...  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  

[193 rows x 12 columns]

In [ ]:
titanic_raw[(titanic_raw.Sex == 'female') & (titanic_raw.Age <= 18)]

PassengerId  Survived  Pclass                                     Name  \
9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)   
10            11         1       3          Sandstrom, Miss. Marguerite Rut   
14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina   
22            23         1       3              McGowan, Miss. Anna "Annie"   
24            25         0       3            Palsson, Miss. Torborg Danira   
..           ...       ...     ...                                      ...   
830          831         1       3  Yasbeck, Mrs. Antoni (Selini Alexander)   
852          853         0       3                  Boulos, Miss. Nourelain   
853          854         1       1                Lines, Miss. Mary Conover   
855          856         1       3               Aks, Mrs. Sam (Leah Rosen)   
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"   

        Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
9    female  14.0      1      0    237736  30.0708   NaN        C  
10   female   4.0      1      1   PP 9549  16.7000    G6        S  
14   female  14.0      0      0    350406   7.8542   NaN        S  
22   female  15.0      0      0    330923   8.0292   NaN        Q  
24   female   8.0      3      1    349909  21.0750   NaN        S  
..      ...   ...    ...    ...       ...      ...   ...      ...  
830  female  15.0      1      0      2659  14.4542   NaN        C  
852  female   9.0      1      1      2678  15.2458   NaN        C  
853  female  16.0      0      1  PC 17592  39.4000   D28        S  
855  female  18.0      0      1    392091   9.3500   NaN        S  
875  female  15.0      0      0      2667   7.2250   NaN        C  

[68 rows x 12 columns]

In [ ]:
## dplyr:arrange
titanic_subset = titanic_raw.drop(['Ticket', 'Cabin'], axis=1)
titanic_subset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
0        0   7.2500        S  
1        0  71.2833        C  
2        0   7.9250        S  
3        0  53.1000        S  
4        0   8.0500        S  
..     ...      ...      ...  
886      0  13.0000        S  
887      0  30.0000        S  
888      2  23.4500        S  
889      0  30.0000        C  
890      0   7.7500        Q  

[891 rows x 10 columns]

In [ ]:
titanic_subset_arranged = titanic_subset.sort_values(by=['Sex', 'Age'], 
                                                     ascending=[False, True])
titanic_subset_arranged

PassengerId  Survived  Pclass  \
803          804         1       3   
755          756         1       2   
78            79         1       2   
831          832         1       2   
305          306         1       1   
..           ...       ...     ...   
727          728         1       3   
792          793         0       3   
849          850         1       1   
863          864         0       3   
888          889         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
803               Thomas, Master. Assad Alexander    male  0.42      0      1   
755                     Hamalainen, Master. Viljo    male  0.67      1      1   
78                  Caldwell, Master. Alden Gates    male  0.83      0      2   
831               Richards, Master. George Sibley    male  0.83      1      1   
305                Allison, Master. Hudson Trevor    male  0.92      1      2   
..                                            ...     ...   ...    ...    ...   
727                      Mannion, Miss. Margareth  female   NaN      0      0   
792                       Sage, Miss. Stella Anna  female   NaN      8      2   
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  female   NaN      1      0   
863             Sage, Miss. Dorothy Edith "Dolly"  female   NaN      8      2   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

         Fare Embarked  
803    8.5167        C  
755   14.5000        S  
78    29.0000        S  
831   18.7500        S  
305  151.5500        S  
..        ...      ...  
727    7.7375        Q  
792   69.5500        S  
849   89.1042        C  
863   69.5500        S  
888   23.4500        S  

[891 rows x 10 columns]

In [ ]:
titanic_subset_arranged.head(10)

PassengerId  Survived  Pclass                             Name   Sex  \
803          804         1       3  Thomas, Master. Assad Alexander  male   
755          756         1       2        Hamalainen, Master. Viljo  male   
78            79         1       2    Caldwell, Master. Alden Gates  male   
831          832         1       2  Richards, Master. George Sibley  male   
305          306         1       1   Allison, Master. Hudson Trevor  male   
164          165         0       3     Panula, Master. Eino Viljami  male   
183          184         1       2        Becker, Master. Richard F  male   
386          387         0       3  Goodwin, Master. Sidney Leonard  male   
788          789         1       3       Dean, Master. Bertram Vere  male   
827          828         1       2            Mallet, Master. Andre  male   

      Age  SibSp  Parch      Fare Embarked  
803  0.42      0      1    8.5167        C  
755  0.67      1      1   14.5000        S  
78   0.83      0      2   29.0000        S  
831  0.83      1      1   18.7500        S  
305  0.92      1      2  151.5500        S  
164  1.00      4      1   39.6875        S  
183  1.00      2      1   39.0000        S  
386  1.00      5      2   46.9000        S  
788  1.00      1      2   20.5750        S  
827  1.00      0      2   37.0042        C

In [ ]:
### Q) 성별(내림차순)/연령(내림차순)/객실등급(오름차순),요금(내림차순)으로 
### 데이터를 복수 정렬하여 
###    titanic_subset_main_arranged 객체를 생성하여 할당하라










titanic_subset_main_arranged = titanic_raw.sort_values(['Sex', 'Age', 'Pclass', 'Fare'], 
                                                        ascending = [False, False, True, False])
titanic_subset_main_arranged

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
..           ...       ...     ...                                   ...   
697          698         1       3      Mullens, Miss. Katherine "Katie"   
502          503         0       3        O'Sullivan, Miss. Bridget Mary   
235          236         0       3          Harknett, Miss. Alice Phoebe   
367          368         1       3        Moussa, Mrs. (Mantoura Boulos)   
19            20         1       3               Masselmani, Mrs. Fatima   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
630    male  80.0      0      0       27042  30.0000   A23        S  
851    male  74.0      0      0      347060   7.7750   NaN        S  
493    male  71.0      0      0    PC 17609  49.5042   NaN        C  
96     male  71.0      0      0    PC 17754  34.6542    A5        C  
116    male  70.5      0      0      370369   7.7500   NaN        Q  
..      ...   ...    ...    ...         ...      ...   ...      ...  
697  female   NaN      0      0       35852   7.7333   NaN        Q  
502  female   NaN      0      0      330909   7.6292   NaN        Q  
235  female   NaN      0      0  W./C. 6609   7.5500   NaN        S  
367  female   NaN      0      0        2626   7.2292   NaN        C  
19   female   NaN      0      0        2649   7.2250   NaN        C  

[891 rows x 12 columns]

In [ ]:
## dplyr:rename
titanic_subset_arranged.head(5)

PassengerId  Survived  Pclass                             Name   Sex  \
803          804         1       3  Thomas, Master. Assad Alexander  male   
755          756         1       2        Hamalainen, Master. Viljo  male   
78            79         1       2    Caldwell, Master. Alden Gates  male   
831          832         1       2  Richards, Master. George Sibley  male   
305          306         1       1   Allison, Master. Hudson Trevor  male   

      Age  SibSp  Parch      Fare Embarked  
803  0.42      0      1    8.5167        C  
755  0.67      1      1   14.5000        S  
78   0.83      0      2   29.0000        S  
831  0.83      1      1   18.7500        S  
305  0.92      1      2  151.5500        S

In [ ]:
titanic_subset_arranged_renamed = 
titanic_subset_arranged.rename({'SibSp': 'Family1', 'Parch':'Family2'}, 
                               axis = 1)

In [ ]:
titanic_subset_arranged_renamed.head(5)

PassengerId  Survived  Pclass                             Name   Sex  \
803          804         1       3  Thomas, Master. Assad Alexander  male   
755          756         1       2        Hamalainen, Master. Viljo  male   
78            79         1       2    Caldwell, Master. Alden Gates  male   
831          832         1       2  Richards, Master. George Sibley  male   
305          306         1       1   Allison, Master. Hudson Trevor  male   

      Age  Family1  Family2      Fare Embarked  
803  0.42        0        1    8.5167        C  
755  0.67        1        1   14.5000        S  
78   0.83        0        2   29.0000        S  
831  0.83        1        1   18.7500        S  
305  0.92        1        2  151.5500        S

In [ ]:
### Q) Sex를 Gender로, Embarked를 PortName으로 변경하라
titanic_raw.rename({'Sex': 'Gender', 'Embarked': 'PortName'}, axis = 1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin PortName  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
## dplyr:mutate
### 요금(Fare)의 평균값을 각 승객의 요금 데이터에서 뺀 후 이 값을 Difference 변수를 생성하여 저장
titanic_subset2 = titanic_subset.assign(Difference = 
                                        lambda x: x.Fare - x.Fare.mean())
titanic_subset2.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch     Fare Embarked  Difference  
0      0   7.2500        S  -24.954208  
1      0  71.2833        C   39.079092  
2      0   7.9250        S  -24.279208  
3      0  53.1000        S   20.895792  
4      0   8.0500        S  -24.154208

In [ ]:
### 요금(Fare)의 평균값을 각 승객의 요금 데이터에서 뺀 후 이 값을 Difference 변수를 생성하여 추출
titanic_subset3 = titanic_subset.Fare - titanic_subset.Fare.mean()
titanic_subset3

0     -24.954208
1      39.079092
2     -24.279208
3      20.895792
4     -24.154208
         ...    
886   -19.204208
887    -2.204208
888    -8.754208
889    -2.204208
890   -24.454208
Name: Fare, Length: 891, dtype: float64

In [ ]:
## dplyr:groupby
titanic_grouped = titanic_subset.groupby(['Survived', 'Sex'])
titanic_grouped

In [ ]:
titanic_grouped[['Age', 'Fare']].apply(lambda x: x.mean())

Age       Fare
Survived Sex                         
0        female  25.046875  23.024385
         male    31.618056  21.960993
1        female  28.847716  51.938573
         male    27.276022  40.821484

In [ ]:
### Q) 객실 등급, 성별을 기준으로 기준을 나눈 후 그들의 생존여부와 평균 나이를 계산하라.



temp = titanic_raw.groupby(['Pclass', 'Sex'])
temp

In [ ]:
temp.apply(lambda x: np.mean(x[['Survived','Age']]))

Survived        Age
Pclass Sex                        
1      female  0.968085  34.611765
       male    0.368852  41.281386
2      female  0.921053  28.722973
       male    0.157407  30.740707
3      female  0.500000  21.750000
       male    0.135447  26.507589

In [ ]:
## dplyr:pipeline
titanic_summarized2 = titanic_subset.groupby(['Survived', 'Sex']).apply(lambda x: x.mean())
titanic_summarized2

PassengerId  Survived    Pclass        Age     SibSp  \
Survived Sex                                                            
0        female   434.851852       0.0  2.851852  25.046875  1.209877   
         male     449.121795       0.0  2.476496  31.618056  0.440171   
1        female   429.699571       1.0  1.918455  28.847716  0.515021   
         male     475.724771       1.0  2.018349  27.276022  0.385321   

                    Parch       Fare  
Survived Sex                          
0        female  1.037037  23.024385  
         male    0.207265  21.960993  
1        female  0.515021  51.938573  
         male    0.357798  40.821484

In [ ]:
### Q) 파이프라인 연산자를 활용하여 객실 등급, 성별을 기준으로 기준을 나눈 후 
###    그들의 생존률과 평균 나이를 계산하라.
titanic_raw.groupby(['Pclass', 'Sex']).apply(lambda x: np.mean(x[['Survived','Age']]))

Survived        Age
Pclass Sex                        
1      female  0.968085  34.611765
       male    0.368852  41.281386
2      female  0.921053  28.722973
       male    0.157407  30.740707
3      female  0.500000  21.750000
       male    0.135447  26.507589

In [ ]:
# 11. Sort

sample = np.random.choice(np.arange(1,13), 12, replace=False)
sorted(sample)
sorted(sample, reverse=True)

sampleDF = pd.DataFrame(sample.reshape(4, 3))
sampleDF.iloc[:, 0]
sorted(sampleDF.iloc[:, 0])
sampleDF.iloc[:, 0].rank()
sampleDF.iloc[:, 0].argsort()
sampleDF.sort_values(0, axis=0) # 0열을 정렬
sampleDF.sort_values([0,1], axis=0) #0열,1열을 정렬

samplemat = np.array(sampleDF)
samplemat[samplemat[:,0].argsort(), ]

# 12. 예외상황
np.isnan(np.nan)
pd.isnull(np.nan)

Nvector = np.array([1, 2, np.nan, -np.inf, np.inf, 0])
np.isnan(Nvector)
Nvector[~np.isnan(Nvector)]

np.isinf(Nvector)
Nvector[~np.isinf(Nvector)]

clean = ~np.isnan(Nvector) & ~np.isinf(Nvector)
Nvector[clean]


array([1., 2., 0.])

In [ ]:
# 13. Exercise
CO2 = pd.read_csv('CO2.csv', index_col = 0)
CO2

Plant         Type   Treatment  conc  uptake
1    Qn1       Quebec  nonchilled    95    16.0
2    Qn1       Quebec  nonchilled   175    30.4
3    Qn1       Quebec  nonchilled   250    34.8
4    Qn1       Quebec  nonchilled   350    37.2
5    Qn1       Quebec  nonchilled   500    35.3
..   ...          ...         ...   ...     ...
80   Mc3  Mississippi     chilled   250    17.9
81   Mc3  Mississippi     chilled   350    17.9
82   Mc3  Mississippi     chilled   500    17.9
83   Mc3  Mississippi     chilled   675    18.9
84   Mc3  Mississippi     chilled  1000    19.9

[84 rows x 5 columns]

In [ ]:
#CO2 data
##Plant별 uptake 평균
CO2.head()

Plant    Type   Treatment  conc  uptake
1   Qn1  Quebec  nonchilled    95    16.0
2   Qn1  Quebec  nonchilled   175    30.4
3   Qn1  Quebec  nonchilled   250    34.8
4   Qn1  Quebec  nonchilled   350    37.2
5   Qn1  Quebec  nonchilled   500    35.3

In [ ]:
CO2.Plant

1     Qn1
2     Qn1
3     Qn1
4     Qn1
5     Qn1
     ... 
80    Mc3
81    Mc3
82    Mc3
83    Mc3
84    Mc3
Name: Plant, Length: 84, dtype: object

In [ ]:
CO2.groupby('Plant').apply(lambda x: x.uptake.mean())

Plant
Mc1    18.000000
Mc2    12.142857
Mc3    17.300000
Mn1    26.400000
Mn2    27.342857
Mn3    24.114286
Qc1    29.971429
Qc2    32.700000
Qc3    32.585714
Qn1    33.228571
Qn2    35.157143
Qn3    37.614286
dtype: float64

In [ ]:
##treatment별 uptake 평균의 차이
CO2.Treatment.unique()

array(['nonchilled', 'chilled'], dtype=object)

In [ ]:
CO2.groupby('Treatment').apply(lambda x: x.uptake.mean())

Treatment
chilled       23.783333
nonchilled    30.642857
dtype: float64

In [ ]:
temp = _
temp[1] - temp[0] # nonchilled - chilled

6.859523809523807

In [ ]:
##treatment별, plant별 uptake 평균
### pandas 쉬운 버전
CO2.groupby(['Plant', 'Treatment']).apply(lambda x: x.uptake.mean())

Plant  Treatment 
Mc1    chilled       18.000000
Mc2    chilled       12.142857
Mc3    chilled       17.300000
Mn1    nonchilled    26.400000
Mn2    nonchilled    27.342857
Mn3    nonchilled    24.114286
Qc1    chilled       29.971429
Qc2    chilled       32.700000
Qc3    chilled       32.585714
Qn1    nonchilled    33.228571
Qn2    nonchilled    35.157143
Qn3    nonchilled    37.614286
dtype: float64

In [ ]:
CO2.Treatment.shape

(84,)

In [ ]:
### 어려운 버전
for p in CO2.Plant.unique():
    plant = CO2[CO2.Plant == p]
    for t in CO2.Treatment.unique():
        plant2 = plant[plant.Treatment == t]
        if plant2.shape[0]==0:
            print('There is Nothing    ' + p + ' & ' + t)
            continue
        print('{0} - {1} : mean({2:.2f})'.format(p, t, plant2.uptake.mean()))

Qn1 - nonchilled : mean(33.23)
There is Nothing    Qn1 & chilled
Qn2 - nonchilled : mean(35.16)
There is Nothing    Qn2 & chilled
Qn3 - nonchilled : mean(37.61)
There is Nothing    Qn3 & chilled
There is Nothing    Qc1 & nonchilled
Qc1 - chilled : mean(29.97)
There is Nothing    Qc2 & nonchilled
Qc2 - chilled : mean(32.70)
There is Nothing    Qc3 & nonchilled
Qc3 - chilled : mean(32.59)
Mn1 - nonchilled : mean(26.40)
There is Nothing    Mn1 & chilled
Mn2 - nonchilled : mean(27.34)
There is Nothing    Mn2 & chilled
Mn3 - nonchilled : mean(24.11)
There is Nothing    Mn3 & chilled
There is Nothing    Mc1 & nonchilled
Mc1 - chilled : mean(18.00)
There is Nothing    Mc2 & nonchilled
Mc2 - chilled : mean(12.14)
There is Nothing    Mc3 & nonchilled
Mc3 - chilled : mean(17.30)


In [ ]:
#Titanic 생존자와 사망자의 평균 연령 차이
titanic_raw = pd.read_csv('train.csv')
titanic_raw.groupby('Survived').apply(lambda x: x.Age.mean())
temp = _
temp[0] - temp[1] # 죽은사람 - 산사람

2.282489590110604

In [ ]:
# 15. Time
from datetime import datetime
from pytz import timezone

datetime.now(timezone('Asia/Seoul'))
SysTime = datetime.now()
SysTime

datetime.datetime(2020, 10, 30, 18, 59, 39, 389221)

In [ ]:
type(SysTime)

datetime.datetime

In [ ]:
# datetime - datetime 같이 뺴기 연산을 하면 timedelta 객체로 변경되어 나온다.
(SysTime - datetime(1970,1,1)).total_seconds()/(60*60*24*365)
delta_t = SysTime - datetime(1970,1,1)
delta_t

datetime.timedelta(days=18565, seconds=68379, microseconds=389221)

In [ ]:
dir(delta_t)

['__abs__',
 '__add__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 'days',
 'max',
 'microseconds',
 'min',
 'resolution',
 'seconds',
 'total_seconds']

In [ ]:
#strptime Ex.
DateTime = "26, Apr, 2018 13:17"
DateTime

'26, Apr, 2018 13:17'

In [ ]:
type(DateTime)

str

In [ ]:
DateTime2 = datetime.strptime(DateTime, "%d, %b, %Y %H:%M")
DateTime2

datetime.datetime(2018, 4, 26, 13, 17)

In [ ]:
type(DateTime2)

datetime.datetime

In [ ]:
DateTime2 - DateTime2

datetime.timedelta(0)

In [ ]:
# etc. Ex.
x = datetime.strptime("2018-03-31", "%Y-%m-%d")
y = datetime.strptime("2018-11-17", "%Y-%m-%d")
y - x # 231일 차이

datetime.timedelta(days=231)

In [ ]:
#https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
SysTimeGmt = datetime.now(timezone('GMT'))
SysTimeGmt

datetime.datetime(2020, 10, 30, 10, 8, 44, 997451, tzinfo=<StaticTzInfo 'GMT'>)

In [ ]:
SysTimeSeoul = datetime.now(timezone('Asia/Seoul'))
SysTimeSeoul

datetime.datetime(2020, 10, 30, 19, 8, 45, 627172, tzinfo=<DstTzInfo 'Asia/Seoul' KST+9:00:00 STD>)

In [ ]:
# week number
SysTimeSeoul.isocalendar()[1]

44

In [ ]:
# 16. UDF

def data_manipulation(address, type, outputname):
    # importing data
    if type == 'csv':
        df_input = pd.read_csv(address)
    elif type == 'txt':
        df_input = pd.read_csv(address, sep=' ')
    else:
        df_input = pd.read_excel(address)
    # colnames, rownames
    df_input.index = [i + 1 for i in range(df_input.shape[0])]
    df_input.columns = ['col ' + str(i + 1) for i in range(df_input.shape[1])]
    # NA imputation 
    df_input = df_input.fillna(df_input.median(axis=0))
    df_input = df_input.rename(columns = lambda x: x.replace('col', 'variable'))
    df_input.to_csv(outputname + '.csv')

# data_manipulation("output.txt","txt","new_output_py")
data_manipulation("train.csv","csv","new_titanic_py")

In [ ]:
#### Type Your Code ####
# 자유롭게 UDF를 만들어보세요.
# Argument로 원하는 파일을 불러오고, 원하는 전처리를 수행하고, 원하는 파일명으로 저장하는 기능을 넣을 것!
########################
import pandas as pd
import numpy as np

def udf_code(inputname, filetype, outputname):
    ## 파일 불러오기
    if filetype == 'txt':
        df = pd.read_table(address)
        #df = pd.read_csv(address, delimiter = '\t')
    elif filetype == 'csv':
        df == pd.read_csv(address)
    else: #filetype == 'excel'
        df == pd.read_excel(address)
    
    ## 전처리
    #인덱스 초기화
    df.reset_index(inplace = True)
    #이상치 처리 (수치형)
    for column in df.columns:
        if df[column] != object:
            
            quartile_1 = np.percentile(df[column].values, 25)
            quartile_3 = np.percentile(df[column].values, 75)

            IQR = quartile_3 - quartile_1
            IQR_weight = IQR *1.5
            lower_bound = quartile_1 - IQR_weight
            upper_bound = quartile_3 + IQR_weight

            #이상치 식별
            outliers = (df[column] < lower_bound) | (df[column] > upper_bound)
            
            # 이상치를 중앙값으로 대체
            median = np.median(df[column].values)
            df.loc[outliers, column] = median
    #결측치 처리
    df = df.fillna(0)

    #output 저장
    df.to_csv(outputname + '.csv')

#udf 실행
udf_code('train.csv', 'csv', 'final')



UnboundLocalError: local variable 'df' referenced before assignment